// Copyright 2026 Figamore (https://github.com/figamore)
// SPDX-License-Identifier: GPL-3.0-only

#pragma once


#ifndef FLUIDMONITOR_ENABLE_SHUTDOWN
#define FLUIDMONITOR_ENABLE_SHUTDOWN 0
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_GPIO
#define FLUIDMONITOR_SHUTDOWN_GPIO 17
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_HOLD_MS
#define FLUIDMONITOR_SHUTDOWN_HOLD_MS 10200
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_DOUBLE_TAP_MS
#define FLUIDMONITOR_SHUTDOWN_DOUBLE_TAP_MS 650
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_TAP_LOCKOUT_MS
#define FLUIDMONITOR_SHUTDOWN_TAP_LOCKOUT_MS 60
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_PULLUP
#define FLUIDMONITOR_SHUTDOWN_PULLUP 0
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_DEBUG
#define FLUIDMONITOR_SHUTDOWN_DEBUG 0
#endif

#ifndef FLUIDMONITOR_SHUTDOWN_DEBUG_STATUS_MS
#define FLUIDMONITOR_SHUTDOWN_DEBUG_STATUS_MS 1000
#endif

#define CYD_PROFILE_AUTO 0
#define CYD_PROFILE_ST7789_CST816S 1
#define CYD_PROFILE_ILI9341_FT5X06 2
#define CYD_PROFILE_ILI9341_XPT2046 3
#define CYD_PROFILE_ST7789_XPT2046 4

#ifndef CYD_HARDWARE_PROFILE
#define CYD_HARDWARE_PROFILE CYD_PROFILE_AUTO
#endif

#define CYD_TFT_SCLK 14
#define CYD_TFT_MOSI 13
#define CYD_TFT_MISO 12
#define CYD_TFT_CS 15
#define CYD_TFT_DC 2
#define CYD_TFT_RST -1
#define CYD_TFT_BL 27
#define CYD_BACKLIGHT_INVERT 0
#define CYD_PANEL_INVERT 0
#define CYD_PANEL_RGB_ORDER 0
#define CYD_PANEL_OFFSET_ROTATION 0

#define CYD_TOUCH_SDA 33
#define CYD_TOUCH_SCL 32
#define CYD_TOUCH_INT -1
#define CYD_TOUCH_RST 25
#define CYD_TOUCH_ADDR 0x15
#define CYD_TOUCH_I2C_PORT 0
#define CYD_TOUCH_OFFSET_ROTATION 0

// Alternate capacitive board (ILI9341 + FT5x06).
#define CYD_ALT_TFT_BL 21
#define CYD_ALT_TOUCH_INT 36
#define CYD_ALT_TOUCH_ADDR 0x38
#define CYD_ALT_TOUCH_I2C_PORT 1

// Resistive board (XPT2046 on a second SPI bus).
#define CYD_RES_TFT_BL 21
#define CYD_RES_PANEL_OFFSET_ROTATION 2
#define CYD_RES_ST7789_PANEL_OFFSET_ROTATION 0
#define CYD_RES_TOUCH_X_MIN 300
#define CYD_RES_TOUCH_X_MAX 3900
#define CYD_RES_TOUCH_Y_MIN 3700
#define CYD_RES_TOUCH_Y_MAX 200
#define CYD_RES_TOUCH_INT -1
#define CYD_RES_TOUCH_SPI_HOST -1
#define CYD_RES_TOUCH_SCLK 25
#define CYD_RES_TOUCH_MOSI 32
#define CYD_RES_TOUCH_MISO 39
#define CYD_RES_TOUCH_CS 33
#define CYD_RES_TOUCH_OFFSET_ROTATION 0
#define CYD_RES_ST7789_TOUCH_OFFSET_ROTATION 2

#ifndef CYD_BOARD_CAPACITIVE
#if CYD_HARDWARE_PROFILE == CYD_PROFILE_ILI9341_XPT2046 || CYD_HARDWARE_PROFILE == CYD_PROFILE_ST7789_XPT2046
#define CYD_BOARD_CAPACITIVE 0
#else
#define CYD_BOARD_CAPACITIVE 1
#endif
#endif

#define CYD_BATTERY_ADC CYD_BOARD_CAPACITIVE
#define CYD_BATTERY_ADC_PIN 39
#define CYD_BATTERY_ADC_MULTIPLIER_NUM 1534
#define CYD_BATTERY_ADC_MULTIPLIER_DEN 1000
#define UI_SPLASH_MS 1000


#define UI_ACTIVE_BRIGHTNESS 255
